Add option for direct path to pci.ids
jaypipes/pcidb pull request #24
Opened 2021-01-21 18:44 UTC by pearsonk

For systems placing the pci.ids database in a location other than
<chroot>/usr/share/misc/pci.ids

Signed-off-by: Kevin Pearson <kevin.pearson@ortmanconsulting.com>

2021-01-21 18:47 UTC, pearsonk commented
This accommodates systems like OpenXT that store the PCI database in unconventional locations, or development systems that wish to use the database of a target system without reconfiguring the host environment.

2021-01-22 15:04 UTC, jaypipes requested changes
Little naming suggestion, otherwise this is awesome, thank you @pearsonk!

In prep for the v0.6.0 release, once this is merged I'll update the README docs to explain the various options that allow discovering/overriding the PCIIDS file.

2021-01-22 15:04 UTC, jaypipes commented on context.go
> +		directPath:          *merged.DirectPath,
How about we call this just `Path` instead of `DirectPath`? since it's an option, if `Path` is set, it overrides any of the auto-discovery features.

2021-01-22 18:31 UTC, pearsonk commented
Had an oops with a git rebase, will resubmit soon

2021-01-22 18:38 UTC, pearsonk commented
Simplified DirectPath to Path, changed behavior to not perform discovery when Path is set.

2021-01-25 12:08 UTC, jaypipes approved these changes
:+1:

2021-01-25 12:08 UTC, merged